### ISSUE TITLE
MissingSceneReferences doesn't actually find missing references

### ISSUE THREAD

**Issue by hybridherbst** [Unity-Technologies/SuperScience#18]
What is it supposed to find?

![image](https://user-images.githubusercontent.com/2693840/64735091-2339c300-d4e8-11e9-9b39-fcf3116e22ec.png)

![image](https://user-images.githubusercontent.com/2693840/64735326-a2c79200-d4e8-11e9-8a8c-5f71aca330ff.png)

**Comment by soraryu** [comment]
Notes: MissingProjectReferences doesn't work either (creating a Prefab out of the above Cube doesn't return anything).
In a larger project, MissingProjectReferences returned some Materials with a missing Texture reference; however, I couldn't find a missing texture slot on the material.
Assigning the same Material to an in-scene object didn't return anything as missing in MissingSceneReferences.

**Comment by mtschoen-unity** [comment]
Thanks for pointing this out. I ended up finding similar situations and have been working on an update here https://github.com/Unity-Technologies/SuperScience/tree/missing-references

**Comment by soraryu** [comment]
Thanks for the update. While it seems to catch the above here's some suggestions:
- doesn't catch missing prefabs right now
- doesn't catch missing material on particle systems (special case - a "none" material in particle systems renders as missing/error)

![unknown](https://user-images.githubusercontent.com/2693840/66498132-e1d40d80-eabd-11e9-85ee-f51769998f6c.png)

**Comment by mtschoen-unity** [comment]
D'oh! There's always _something_! I have been mostly working on these scripts as I need them during my own development process, so if I haven't encountered a particular edge case it is likely missing from these scripts. I can take a look and try to account for these issues next time I have some spare cycles to work on this branch. Part of the reason I haven't opened a PR for these improvements is that every time I come back I find something I didn't account for.

If you have the time and can figure it out, please feel free to branch off of this branch and add this feature. I'd be happy to review a PR against it. Off the top of my head, maybe there is a method in `PrefabUtility` that can check for this?

**Comment by soraryu** [comment]
Happened to use this again and wanted to point out another issue:
Timeline bindings show as missing despite being there,
![image](https://user-images.githubusercontent.com/2693840/71132653-61860300-21f8-11ea-95b1-a0555ae41a9b.png)

I don't have time right now to do a proper PR but might in the future :)

**Comment by mtschoen-unity** [comment]
> Timeline bindings show as missing despite being there

Hm... I wasn't able to replicate this. There may indeed be some missing references that you're just not seeing here. If you see this again, try looking at the debug inspector and see if any properties there are missing references. It may end up being something that is hidden/unused.

I tried to replicate some of the other issues you found but I think this version covers them. I'm opening a PR with these changes to get them on the master branch which will close this issue but please re-open this or create a new issue if you still have issues.
