### ISSUE TITLE
Unity Blog: Broken source links

### ISSUE THREAD

**Issue by onefifth** [Unity-Technologies/SuperScience#20]
This is the entirely wrong place to report this, but I don't know where the correct place is.

There's a great [post](https://blogs.unity3d.com/2019/04/03/tips-for-extending-the-unity-editor-lessons-from-project-mars/) on the Unity blog containing a number of example links to this SuperScience repo. 
Many of the links in of the example links in the post now 404, pointing to files that were moved in commit c3c70e88eb40ee.

Fixing these links for future readers would be fantastic!

**Comment by mtschoen-unity** [comment]
Thanks for spotting this! I have sent a request to get this fixed. We should have updated links on that post in the next few days.

**Comment by mtschoen-unity** [comment]
Links are fixed! Thanks again for letting us know 👍
