### ISSUE TITLE
Packaging the repo into a unityPackage

### ISSUE THREAD

**Issue by Mikerr1111** [Unity-Technologies/SuperScience#4]
Since SuperScience is in experimental support would there be any issues in turning the asset repository into a unityPackage?  Or would it be fine as long as the latest version of Unity in this case Unity 2018.1 is used.

**Comment by AndrewTHEManeri** [comment]
I don't foresee any issues doing that.  Are you asking to do it for your own personal use or if we are planning on doing unityPackage releases like we do with EditorVR?

**Comment by Mikerr1111** [comment]
Mainly for personal use but since you mention it are there plans for a unitPackage like EditorVR down the road when support is no longer the experimental phase?

**Comment by Mikerr1111** [comment]
I'm going to close this issue since you answered my question earlier.
